export const copy = {
  common: {
    loading: '내용을 불러오는 중이에요',
    retry: '다시 시도',
    save: '저장',
    cancel: '취소',
    edit: '수정',
    delete: '삭제',
    back: '뒤로',
    next: '다음',
    done: '완료',
    yes: '예',
    no: '아니요',
    selected: '선택됨',
    notSelected: '선택 안 됨',
  },
  nav: {
    today: '오늘',
    records: '기록',
    together: '함께',
    settings: '설정',
    loading: '메뉴 자리표시자',
    error: '메뉴를 열지 못했어요',
    accessibility: '주요 메뉴',
  },
  header: {
    loading: '제목을 준비하는 중이에요',
    error: '제목을 표시하지 못했어요',
  },
  setup: {
    title: '처음 설정',
    accountStep: '1 / 3',
    modeStep: '2 / 3',
    speechStep: '3 / 3',
    accountQuestion: '내 계정을 준비할까요?',
    accountDescription: '이 기기에서 안전하게 기록을 시작해요.',
    accountAction: '내 계정 시작하기',
    modeQuestion: '화면을 어떻게 볼까요?',
    speechQuestion: '화면 내용을 읽어드릴까요?',
    speechOn: '읽어주기 켜기',
    speechOff: '읽어주기 끄기',
    finishTitle: '준비가 끝났어요',
    connect: '지원자 연결하기',
    later: '나중에',
    error: '설정을 저장하지 못했어요',
    accountLoadError: '계정을 불러오지 못했어요',
    accountPrepareError: '계정을 준비하지 못했어요',
    updateError: '설정을 바꾸지 못했어요',
  },
  mode: {
    title: '화면 보기',
    easy: '쉬운 모드',
    easyDescription: '큰 글자와 큰 버튼으로 한 가지씩 보여줘요.',
    standard: '일반 모드',
    standardDescription: '여러 내용을 한눈에 보여줘요.',
    loading: '설정을 불러오는 중이에요',
    error: '설정을 바꾸지 못했어요',
    empty: '선택 전',
  },
  today: {
    title: '오늘',
    brand: '하루한칸',
    subtitle: '오늘도 내 속도로 하나씩 해봐요.',
    week: '이번 주',
    summary: (completed: number, total: number) => `오늘 ${total}개 중 ${completed}개 기록했어요`,
    morning: '아침 루틴',
    daytime: '낮 루틴',
    evening: '저녁 루틴',
    anytime: '시간 미정',
    section: '오늘 할 일',
    manage: '할 일 관리',
    add: '새 할 일',
    weight: '체중 기록',
    recorded: '✓ 기록했어요',
    undoRecorded: '기록했어요',
  },
  task: {
    listTitle: '내 할 일',
    editorNewTitle: '할 일 추가',
    editorEditTitle: '할 일 바꾸기',
    loading: '할 일을 불러오는 중이에요',
    error: '할 일을 불러오지 못했어요',
    empty: '아직 할 일이 없어요',
    itemError: '이 할 일을 불러오지 못했어요',
    itemEmpty: '표시할 할 일이 없어요',
    saving: '기록하는 중이에요',
    saveError: '기록하지 못했어요. 다시 눌러 주세요',
    beforeChoice: '선택 전',
    complete: '했어요',
    medicationComplete: '먹었다고 기록',
    delay: '나중에',
    help: '도움 필요',
    delayedRecorded: '나중에로 기록했어요',
    helpRecorded: '도움 필요로 기록했어요',
    supporterAdded: '지원자가 추가했어요 · 내가 수정할 수 있어요',
    moveUp: '위로',
    moveDown: '아래로',
    reorder: '순서 이동',
    whatChange: '무엇을 바꿀까요?',
    nameAndIcon: '이름·그림',
    time: '시간',
    repeat: '반복 요일',
    reminder: '알림',
    color: '색',
    name: '이름',
    kind: '종류',
    standardKind: '일반 할 일',
    medicationKind: '약 일정',
    prepare: '할 일을 준비하는 중이에요',
    editorError: '저장하지 못했어요. 적은 내용은 그대로 있어요',
    editorEmpty: '새 할 일 기본값',
    required: '이름을 적어 주세요',
    chooseScope: '어느 때부터 바꿀까요?',
    todayOnly: '오늘만',
    fromToday: '오늘부터 계속',
    review: '확인하고 저장해요',
    previous: '이전',
    step: (current: number, total: number) => `${current} / ${total}`,
    deleteQuestion: (title: string) => `‘${title}’을 지울까요? 지운 뒤에도 되돌릴 수 있어요.`,
    deleted: '할 일을 지웠어요',
    restored: '할 일을 되돌렸어요',
    reorderError: '순서를 바꾸지 못했어요. 원래 순서로 돌아갔어요',
    deleteError: '할 일을 지우지 못했어요',
    everyDay: '매일',
    noRepeat: '반복 없음',
    repeatSummary: (days: readonly string[]) => days.join(' · '),
  },
  picker: {
    loading: '선택지를 불러오는 중이에요',
    error: '그림을 불러오지 못했어요',
    empty: '그림을 골라 주세요',
    iconTitle: '그림',
    colorTitle: '색',
    more: '더 보기',
    sage: '세이지',
    lavender: '라벤더',
    sky: '스카이',
    butter: '버터',
    toothbrush: '양치',
    walking: '걷기',
    shower: '씻기',
    medicine: '약',
  },
  schedule: {
    title: '일정',
    loading: '일정을 불러오는 중이에요',
    error: '일정을 표시하지 못했어요',
    empty: '시간 없음 · 반복 없음',
    time: '시간',
    medicationTime: '약 알림 시간',
    days: '반복 요일',
    reminder: '알림',
    reminderOn: '알림 켜짐',
    reminderOff: '알림 꺼짐',
    weekdays: ['월', '화', '수', '목', '금', '토', '일'],
  },
  medication: {
    loading: '약 사진을 준비하는 중이에요',
    error: '사진을 불러오지 못했어요',
    empty: '약 사진을 추가해 주세요',
    photoAlt: '등록한 약 사진',
    addPhoto: '사진 추가',
    changePhoto: '사진 바꾸기',
    removePhoto: '사진 지우기',
    displayName: '표시 이름',
    safety: '앱의 알림만 바뀌어요. 복용 방법은 의사·약사의 안내를 따라요.',
    confirm: '안내를 확인했어요',
    changeSummary: (scope: string, time: string) => `${scope} · 새 시간 ${time}`,
    supporterNotice: '지원자에게도 변경 내용이 보여요',
    detailError: '약 정보를 불러오지 못했어요',
    saveFirst: '약 일정을 먼저 저장해 주세요',
    taskMissing: '약 일정을 찾지 못했어요',
  },
  weight: {
    title: '체중 기록',
    question: '오늘 몸무게를 적어 주세요',
    unit: 'kg',
    previous: '지난 기록',
    recent: '최근 체중 기록',
    loading: '지난 기록을 불러오는 중이에요',
    error: '저장하지 못했어요',
    empty: '숫자 입력 전',
    invalid: '숫자를 다시 확인해 주세요',
    saved: '체중을 기록했어요',
    loadError: '체중 기록을 불러오지 못했어요',
  },
  records: {
    title: '내 기록',
    weekly: '주간',
    monthly: '월간',
    task: '할 일',
    weekLabel: (year: number, month: number, week: number) => `${year}년 ${month}월 · ${week}주`,
    monthLabel: (year: number, month: number) => `${year}년 ${month}월`,
    completedCount: (count: number) => `완료 ${count}회`,
    weeklyCellLabel: (task: string, weekday: string, status: string) => `${task}, ${weekday}요일, ${status}`,
    monthlyCellLabel: (task: string, year: number, month: number, day: number, weekday: string, status: string) => `${task}, ${year}년 ${month}월 ${day}일 ${weekday}요일, ${status}`,
    previousWeek: '이전 주',
    nextWeek: '다음 주',
    previousMonth: '이전 달',
    nextMonth: '다음 달',
    loading: '기록을 불러오는 중이에요',
    error: '기록을 불러오지 못했어요',
    empty: '아직 보여줄 기록이 없어요',
    complete: '✓ 완료',
    missing: '○ 기록 없음',
    notScheduled: '— 예정 없음',
    completeStatus: '완료',
    missingStatus: '기록 없음',
    notScheduledStatus: '예정 없음',
  },
  support: {
    title: '함께 관리',
    one: '지원자 1명',
    connected: '연결되어 있어요',
    loading: '연결 정보를 불러오는 중이에요',
    error: '연결 정보를 불러오지 못했어요',
    empty: '연결된 지원자가 없어요',
    invite: '지원자 초대하기',
    invitePrompt: '초대할 지원자의 정보를 적어 주세요',
    shared: '공유하는 내용',
    scheduleView: '일정 보기',
    scheduleAdd: '일정 추가',
    scheduleUpdate: '일정 수정',
    recordsView: '생활 체크 보기',
    weightView: '체중 보기',
    medicationView: '약 일정 보기',
    selfOnly: '완료 체크는 나만 할 수 있어요',
    history: '변경 내역 보기',
    disconnect: '지원자 연결 끊기',
    disconnectExplain: '연결을 끊으면 앞으로 새 일정과 기록이 공유되지 않아요.',
    disconnectConfirm: '정말 연결을 끊을까요?',
    inviteError: '지원자를 초대하지 못했어요',
    permissionError: '공유 설정을 바꾸지 못했어요',
    disconnectError: '지원자 연결을 끊지 못했어요',
  },
  history: {
    title: '변경 내역',
    today: '오늘',
    loading: '변경 내역을 불러오는 중이에요',
    error: '변경 내역을 불러오지 못했어요',
    empty: '아직 바뀐 내용이 없어요',
    open: '관련 할 일 보기',
    detail: '자세히 보기',
    ownerActor: '내가',
    supporterActor: (name: string) => `${name} 지원자가`,
    targetTask: '할 일',
    targetRecurrence: '반복 일정',
    targetOverride: '하루 일정',
    targetMedication: '약 정보',
    targetSupport: '지원자 연결',
  },
  settings: {
    title: '사용 설정',
    speech: '읽어주기',
    speechDescription: '화면 제목과 선택한 내용을 읽어줘요.',
    brightness: '화면 밝기',
    system: '시스템',
    light: '밝게',
    dark: '어둡게',
    signedOut: '로그아웃',
    updateError: '설정을 바꾸지 못했어요',
  },
  readAloud: {
    loading: '읽을 내용을 준비하는 중이에요',
    error: '지금은 읽어드릴 수 없어요',
    disabled: '읽어주기 꺼짐',
    start: '🔊 읽어주기',
    stop: '⏹ 그만 읽기',
  },
  shell: {
    loading: '콘텐츠 자리표시자',
    error: '화면을 열지 못했어요',
  },
  undo: {
    loading: '처리 중이에요',
    error: '되돌리지 못했어요',
    action: '되돌리기',
    dismiss: '닫기',
    remaining: (seconds: number) => `${seconds}초`,
  },
} as const
